# Generated by Django 2.2.5 on 2019-10-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20191021_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomodel',
            name='selection',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
