# Generated by Django 2.2.5 on 2019-10-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audiomodel_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomodel',
            name='Text',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
